### ISSUE TITLE
Login option to hyperland wont show in Ubuntu Lts 24.04

### ISSUE THREAD

**Issue by OthmanHaba** [JaKooLit/Debian-Hyprland#83]
the installation of HyperLand on a freshly installed Ubuntu 24.04 LTS system. The installation process was followed as per the instructions, but unfortunately, HyperLand did not appear as an option in the login screen after the installation.

**Comment by OthmanHaba** [comment]
here is my loging file 
[Install-Logs.zip](https://github.com/JaKooLit/Debian-Hyprland/files/15371104/Install-Logs.zip)

**Comment by JaKooLit** [comment]
install-logs are empty

and a reminder, you installed using the Ubuntu-Hyprland branch from this repo?

**Comment by JaKooLit** [comment]
https://github.com/JaKooLit/Debian-Hyprland/tree/Ubuntu-24.04-LTS

**Comment by OthmanHaba** [comment]
yes i have installed via the Ubuntu-branch

**Comment by JaKooLit** [comment]
ok.. Your attached logs is empty. nothing in there

**Comment by krauchelli** [comment]
it seemed that i have the same problem. After finished installing and wrapping up everything, i accepted the suggestion to reboot, then logged in with the usual greeter, still showing the same DE before hyprland. 

I am using Kubuntu 24.04 LTS.

On the other hand... it seems that it can be useful in my hand because i still want the KDE be my main DE if something happens. For now i'll just went to tty (CTRL + ALT + F3), then enter Hyprland command line to start the hyprland from there.

**Comment by JaKooLit** [comment]
> it seemed that i have the same problem. After finished installing and wrapping up everything, i accepted the suggestion to reboot, then logged in with the usual greeter, still showing the same DE before hyprland.
> 
> I am using Kubuntu 24.04 LTS.
> 
> On the other hand... it seems that it can be useful in my hand because i still want the KDE be my main DE if something happens. For now i'll just went to tty (CTRL + ALT + F3), then enter Hyprland command line to start the hyprland from there.

choose Hyprland on Login Manager...

on GDM, after clicking your user name , on the bottom right click that one and choose hyprland


on SDDM, choose Hyprland....

chances are, you have autologin enabled hence you are booting into your default DE
