### ISSUE TITLE
[Uninstall]: SHow do I uninstall Hyprland?

### ISSUE THREAD

**Issue by JoaoVictorLong** [JaKooLit/Debian-Hyprland#99]
Hey there,

I have same problems with my nvidia like I saw in README. Anyone know how to uninstall hyprLand on Debian?

Thanks!

**Comment by TerminatedProcess** [comment]
I know I'm not exactly answering your question as I don't think there is a way to uninstall it. I think the README says this. But you should look into Timeshift and backup frequently so you can just roll back.

**Comment by JaKooLit** [comment]
as stated by @TerminatedProcess 

I didnt provide any uninstall script since it causes lots of issues when I test..

but if you just want to remove the Hyprland only or any packages which are downloaded and built from source cd into Hyprland and a sudo make uninstall command should remove the Hyprland..

All depends on the packages.. the link for a source package are on readme.. different packages, different way to uninstall it.

you need to go through each packages readme to uninstall it.

**Comment by JoaoVictorLong** [comment]
Nice Guys, thansks for the answer!

I will try do this and  new work with Hyprland @JaKooLit !
